<a href="https://colab.research.google.com/github/impashree/SVR/blob/main/Artifical_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing libraries

In [68]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.9.2'

importing dataset

In [69]:
df=pd.read_csv('Churn_Modelling.csv')
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Label encoding the "Gender"

In [70]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


OneHotEncoding the "Geography"

In [71]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


splitting the dataset into train and test set

In [72]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)



feature scaling

In [73]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

initalizing the ANN

In [74]:
ann=tf.keras.models.Sequential()


adding the input layer and the first hidden layer

In [75]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the second hidden layer

In [76]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the output layer

In [77]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

compiling the ANN

In [81]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

training the ANN on train set

In [83]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5229 - accuracy: 0.7931
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4557 - accuracy: 0.7979
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4317 - accuracy: 0.8086
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4154 - accuracy: 0.8194
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4036 - accuracy: 0.8269
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3933 - accuracy: 0.8289
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3852 - accuracy: 0.8292
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3797 - accuracy: 0.8294
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3749 - accuracy: 0.8309
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3696 - accura

predicting the test set results

In [84]:
ypred=ann.predict(x_test)
ypred=(ypred>0.5)
print(np.concatenate((ypred.reshape(len(ypred),1),y_test.reshape(len(y_test),1)),1))


63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


confusion matrix

In [85]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,ypred)
print(cm)
accuracy_score(y_test,ypred)

[[1512   83]
 [ 203  202]]


0.857